--- #default
config:
  options:
    use-default-async: true # common 에 선언된 async executor 를 사용할지 여부
    vault-type: native  # native library 사용
    auth-strategy: session  # 인증 유지 방법
  constants:
    application-name: ${APPLICATION_NAME:base-backend}
    application-version: ${APPLICATION_VERSION:0.0.1}
    common-crypto-key: ${COMMON_CRYPTO_KEY:temporary_crypto_key}
    sse-emitter-timeout-ms: ${SSE_EMITTER_TIMEOUT_MS:60000}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  application:
    name: ${config.constants.application-name}
  config:
    import: optional:file:../.env[.properties]
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:${DATABASE_SERVER_PORT:3306}/${DATABASE_NAME:base_backend}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: false
        globally_quoted_identifiers: true   # 예약어 컬럼, 테이블 이름에 대한 예외 처리 ( id.. )
        globally_quoted_identifiers_skip_column_definitions: true   # 예약어 컬럼, 테이블 이름에 대한 예외 처리 ( id.. )
        jdbc:
          time_zone: UTC  # DB timezone 정보를 UTC 로 설정
    open-in-view: false # OSIV 를 적용하지 않음 - 영속성 컨텍스트를 실제 트랜잭션 범위로만 한정 시킴
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      encoding: UTF-8

server:
  port: ${APP_SERVER_PORT:7479}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 30m  # 세션 타임아웃: 30분

jasypt:
  encryptor:
    bean: "commonJasyptEncryptor"

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: "api.html" # http://localhost:{port}/api.html
    operations-sorter: "method"
    default-models-expand-depth: 0  # 하단 schema 영역을 닫아둠

management:
  endpoints:
    web:
      base-path: "/monitor"
      exposure:
        include: health, info

logging:
  level:
    com.kelly.base: ${KELLY_LOG_LEVEL:INFO}
