# dependency 확인 - https://docs.spring.io/spring-boot/4.0/appendix/dependency-versions/index.html
[versions]
spring-boot = "4.0.0"
spring-dependency = "1.1.7"

annotation-api = "3.0.0"
persistence-api = "3.2.0"
querydsl = "5.1.0"

maven-settings = "0.5"
sonarqube = "3.5.0.2730"

jasypt = "3.0.5"
springdoc = "3.0.0"
nanoid = "1.0.1"
spring-modulith = "2.0.0"

# Vulnerability 보완 적용 ( 아래에 작성후 bundle -> clear-vulnerabilities 에 업데이트 )


[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency = { id = "io.spring.dependency-management", version.ref = "spring-dependency" }
maven-settings = { id = "net.linguica.maven-settings", version.ref = "maven-settings" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }

[bundles]
clear-vulnerabilities = []

[libraries]
# spring version dependency - automatic
spring-boot-starter-webmvc = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc" }
spring-boot-starter-webmvc-test = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc-test" }
spring-boot-starter-security = { group = "org.springframework.boot", name = "spring-boot-starter-security" }
spring-boot-starter-security-test = { group = "org.springframework.boot", name = "spring-boot-starter-security-test" }
spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
spring-boot-starter-data-jpa-test = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa-test" }
spring-boot-starter-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
spring-boot-starter-actuator-test = { group = "org.springframework.boot", name = "spring-boot-starter-actuator-test" }
spring-boot-starter-cache = { group = "org.springframework.boot", name = "spring-boot-starter-cache" }
spring-boot-starter-cache-test = { group = "org.springframework.boot", name = "spring-boot-starter-cache-test" }
spring-boot-starter-integration = { group = "org.springframework.boot", name = "spring-boot-starter-integration" }
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
spring-boot-configuration-processor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
lombok = { group = "org.projectlombok", name = "lombok" }
mariadb-java-client = { group = "org.mariadb.jdbc", name = "mariadb-java-client" }
h2 = { group = "com.h2database", name = "h2" }

# user-defined versioning
jasypt = { group = "com.github.ulisesbocchio", name = "jasypt-spring-boot-starter", version.ref = "jasypt" }
springdoc = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
nanoid = { group = "io.viascom.nanoid", name = "nanoid", version.ref = "nanoid" }
spring-modulith-starter-core = { group = "org.springframework.modulith", name = "spring-modulith-starter-core", version.ref = "spring-modulith" }
spring-modulith-starter-test = { group = "org.springframework.modulith", name = "spring-modulith-starter-test", version.ref = "spring-modulith" }
spring-modulith-docs = { group = "org.springframework.modulith", name = "spring-modulith-docs", version.ref = "spring-modulith" }

# special versioning targets
## 아래 항목들은 spring boot 버전의 dependency 에 맞게 업데이트 필요함
annotation-api = { group = "jakarta.annotation", name = "jakarta.annotation-api", version.ref = "annotation-api" }
persistence-api = { group = "jakarta.persistence", name = "jakarta.persistence-api", version.ref = "persistence-api" }
querydsl-jpa = { group = "com.querydsl", name = "querydsl-jpa", version.ref = "querydsl" }
querydsl-apt = { group = "com.querydsl", name = "querydsl-apt", version.ref = "querydsl" }

# Vulnerability 보완 부분 ( 아래에 작성 )
