# dependency 확인 - https://docs.spring.io/spring-boot/3.5/appendix/dependency-versions/index.html
[versions]
spring-boot = "3.5.7"
spring-dependency = "1.1.7"

annotation-api = "2.1.1"
persistence-api = "3.1.0"
querydsl = "5.1.0"

openapi-gradle-plugin = "1.6.0"
maven-settings = "0.5"
sonarqube = "3.5.0.2730"

jasypt = "3.0.5"
springdoc = "2.8.13"
nanoid = "1.0.1"

# Vulnerability 보완 적용 ( 아래에 작성후 bundle -> clear-vulnerabilities 에 업데이트 )
commons-lang3 = "3.19.0"


[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency = { id = "io.spring.dependency-management", version.ref = "spring-dependency" }
openapi-gradle-plugin = { id = "org.springdoc.openapi-gradle-plugin", version.ref = "openapi-gradle-plugin" }
maven-settings = { id = "net.linguica.maven-settings", version.ref = "maven-settings" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }

[bundles]
clear-vulnerabilities = ["commons-lang3"]

[libraries]
# spring version dependency - automatic
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-boot-starter-security = { group = "org.springframework.boot", name = "spring-boot-starter-security" }
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
spring-boot-starter-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
spring-boot-starter-integration = { group = "org.springframework.boot", name = "spring-boot-starter-integration" }
spring-boot-starter-cache = { group = "org.springframework.boot", name = "spring-boot-starter-cache" }
spring-boot-configuration-processor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor" }
spring-integration-http = { group = "org.springframework.integration", name = "spring-integration-http" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
spring-security-test = { group = "org.springframework.security", name = "spring-security-test" }
spring-integration-test = { group = "org.springframework.integration", name = "spring-integration-test" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
lombok = { group = "org.projectlombok", name = "lombok" }
mariadb-java-client = { group = "org.mariadb.jdbc", name = "mariadb-java-client" }
h2 = { group = "com.h2database", name = "h2" }

# user-defined versioning
jasypt = { group = "com.github.ulisesbocchio", name = "jasypt-spring-boot-starter", version.ref = "jasypt" }
springdoc = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
nanoid = { group = "io.viascom.nanoid", name = "nanoid", version.ref = "nanoid" }

# special versioning targets
## 아래 항목들은 spring boot 버전의 dependency 에 맞게 업데이트 필요함
annotation-api = { group = "jakarta.annotation", name = "jakarta.annotation-api", version.ref = "annotation-api" }
persistence-api = { group = "jakarta.persistence", name = "jakarta.persistence-api", version.ref = "persistence-api" }
querydsl-jpa = { group = "com.querydsl", name = "querydsl-jpa", version.ref = "querydsl" }
querydsl-apt = { group = "com.querydsl", name = "querydsl-apt", version.ref = "querydsl" }

# Vulnerability 보완 부분 ( 아래에 작성 )
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang3" }
